# Generated by Django 3.1.1 on 2020-11-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldsrelatedonetoonefield', editable=False, null=True),
        ),
    ]
