# Generated by Django 3.1.1 on 2020-11-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201127_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='', null=True, unique=True),
        ),
    ]
